apiVersion: apps/v1
kind: Deployment
metadata:
  name: gallery
  labels:
    app: gallery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gallery
  template:
    metadata:
      labels:
        app: gallery
    spec:
      containers:
        - name: gallery
          image: image-registry.openshift-image-registry.svc:5000/lab/gallery:latest
          ports:
            - containerPort: 8080
          # These are the variables your Go app requested
          env:
            - name: DB_HOST
              value: "postgres" # Matches the name of the Postgres Service below
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "galleryuser"
            - name: DB_PASS
              value: "gallerypass"
            - name: DB_NAME
              value: "gallerydb"
---
apiVersion: v1
kind: Service
metadata:
  name: gallery
spec:
  selector:
    app: gallery
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          # The Bitnami image runs safely as non-root on OpenShift
          image: docker.io/bitnami/postgresql:15
          ports:
            - containerPort: 5432
          # These initialize the database to match your app's variables
          env:
            - name: POSTGRESQL_USERNAME
              value: "galleryuser"
            - name: POSTGRESQL_PASSWORD
              value: "gallerypass"
            - name: POSTGRESQL_DATABASE
              value: "gallerydb"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432