apiVersion: v1
kind: Secret
metadata:
  name: gallery-secrets
  labels:
    app.kubernetes.io/part-of: gallery-app
type: Opaque
stringData:
  PROD: "true"
  GIN_MODE: "release"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "galleryuser"
  DB_PASS: "gallerypass"
  DB_NAME: "gallerydb"
  SERVER_ADDRESS: "0.0.0.0:8080"
  STORAGE_URI: "seaweedfs:8333"
  STORAGE_BUCKET: "gallery"
  STORAGE_ACCESS_KEY: "some_access_key"
  STORAGE_SECRET_KEY: "some_secret_key"
  JWT_SECRET: "secret"
  JWT_EXPIRATION: "86400"

  POSTGRES_USER: "galleryuser"
  POSTGRES_PASSWORD: "gallerypass"
  POSTGRES_DB: "gallerydb"

  AWS_ACCESS_KEY_ID: "some_access_key"
  AWS_SECRET_ACCESS_KEY: "some_secret_key"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gallery
  labels:
    app: gallery
    app.kubernetes.io/part-of: gallery-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gallery
  template:
    metadata:
      labels:
        app: gallery
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo "waiting for postgres..."; sleep 2; done;']
        - name: wait-for-seaweedfs
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z seaweedfs 8333; do echo "waiting for seaweedfs..."; sleep 2; done;']
      containers:
        - name: gallery
          image: kisbogdan/gallery:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: gallery-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: gallery
  labels:
    app: gallery
    app.kubernetes.io/part-of: gallery-app
spec:
  selector:
    app: gallery
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    app.kubernetes.io/part-of: gallery-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: gallery-secrets
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    app.kubernetes.io/part-of: gallery-app
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: seaweedfs-volume
  labels:
    type: local
    app: seaweedfs
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/seaweedfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs-volume-claim
  labels:
    app: seaweedfs
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaweedfs
  labels:
    app: seaweedfs
    app.kubernetes.io/part-of: gallery-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seaweedfs
  template:
    metadata:
      labels:
        app: seaweedfs
    spec:
      containers:
        - name: seaweedfs
          image: chrislusf/seaweedfs:latest
          command:
            - "weed"
            - "server"
            - "-dir=/data"
            - "-s3"
          ports:
            - containerPort: 9333
            - containerPort: 8080
            - containerPort: 8333
          volumeMounts:
            - mountPath: /data
              name: seaweedfsdata
          envFrom:
            - secretRef:
                name: gallery-secrets
      volumes:
        - name: seaweedfsdata
          persistentVolumeClaim:
            claimName: seaweedfs-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs
  labels:
    app: seaweedfs
    app.kubernetes.io/part-of: gallery-app
spec:
  selector:
    app: seaweedfs
  ports:
    - name: master
      port: 9333
      targetPort: 9333
    - name: volume
      port: 8080
      targetPort: 8080
    - name: s3
      port: 8333
      targetPort: 8333