apiVersion: apps/v1
kind: Deployment
metadata:
  name: gallery
  labels:
    app: gallery
    app.kubernetes.io/part-of: gallery-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gallery
  template:
    metadata:
      labels:
        app: gallery
    spec:
      containers:
        - name: gallery
          image: kisbogdan/gallery:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "galleryuser"
            - name: DB_PASS
              value: "gallerypass"
            - name: DB_NAME
              value: "gallerydb"
            - name: STORAGE_URI
              value: "seaweedfs:8333"
            - name: STORAGE_ACCESS_KEY
              value: "some_access_key"
            - name: STORAGE_SECRET_KEY
              value: "some_secret_key"
---
apiVersion: v1
kind: Service
metadata:
  name: gallery
  labels:
    app: gallery
    app.kubernetes.io/part-of: gallery-app
spec:
  selector:
    app: gallery
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    app.kubernetes.io/part-of: gallery-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "galleryuser"
            - name: POSTGRES_PASSWORD
              value: "gallerypass"
            - name: POSTGRES_DB
              value: "gallerydb"
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    app.kubernetes.io/part-of: gallery-app
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: seaweedfs-volume
  labels:
    type: local
    app: seaweedfs
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/seaweedfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs-volume-claim
  labels:
    app: seaweedfs
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaweedfs
  labels:
    app: seaweedfs
    app.kubernetes.io/part-of: gallery-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seaweedfs
  template:
    metadata:
      labels:
        app: seaweedfs
    spec:
      containers:
        - name: seaweedfs
          image: chrislusf/seaweedfs:latest
          command:
            - "weed"
            - "server"
            - "-dir=/data"
            - "-s3"
          ports:
            - containerPort: 9333
            - containerPort: 8080
            - containerPort: 8333
          volumeMounts:
            - mountPath: /data
              name: seaweedfsdata
          env:
            - name: AWS_ACCESS_KEY_ID
              value: "some_access_key"
            - name: AWS_SECRET_ACCESS_KEY
              value: "some_secret_key"
      volumes:
        - name: seaweedfsdata
          persistentVolumeClaim:
            claimName: seaweedfs-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs
  labels:
    app: seaweedfs
    app.kubernetes.io/part-of: gallery-app
spec:
  selector:
    app: seaweedfs
  ports:
    - name: master
      port: 9333
      targetPort: 9333
    - name: volume
      port: 8080
      targetPort: 8080
    - name: s3
      port: 8333
      targetPort: 8333