# syntax=docker/dockerfile:1

# Build the application from source
FROM golang:1.26 AS build-backend

WORKDIR /app

COPY ./backend ./backend
COPY ./ocr ./ocr
WORKDIR /app/ocr
RUN go mod download

RUN apt update -y && apt install libleptonica-dev libtesseract-dev -y

RUN CGO_ENABLED=1 GOOS=linux go build -o /ocr

# Deploy the application binary into a lean image
FROM debian:trixie-slim AS build-release-stage

RUN apt-get update -y && apt-get install -y tzdata tesseract-ocr && rm -rf /var/lib/apt/lists/*

WORKDIR /

COPY --from=build-backend /ocr /ocr

ENTRYPOINT ["/ocr"]
