apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    app.kubernetes.io/part-of: gallery-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: docker.io/bitnami/postgresql:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_USERNAME
              value: "galleryuser"
            - name: POSTGRESQL_PASSWORD
              value: "gallerypass"
            - name: POSTGRESQL_DATABASE
              value: "gallerydb"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    app.kubernetes.io/part-of: gallery-app
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432