services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
      POSTGRES_DB: gorm
    ports:
      - 5432:5432
  seaweedfs:
    image: chrislusf/seaweedfs:latest
    command: "server -dir=/data -s3"
    environment:
      - AWS_ACCESS_KEY_ID=some_access_key
      - AWS_SECRET_ACCESS_KEY=some_secret_key
    ports:
      - 9333:9333
      - 8333:8333
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
