apiVersion: apps/v1
kind: Deployment
metadata:
  name: gallery-ocr
  labels:
    app: gallery-ocr
    app.kubernetes.io/part-of: gallery-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gallery-ocr
  template:
    metadata:
      labels:
        app: gallery-ocr
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            [
              "sh",
              "-c",
              "until nc -z postgres 5432; do echo \"waiting for postgres...\";
                sleep 2; done;",
            ]
        - name: wait-for-seaweedfs
          image: busybox:1.36
          command:
            [
              "sh",
              "-c",
              "until nc -z seaweedfs 8333; do echo \"waiting for
                seaweedfs...\"; sleep 2; done;",
            ]
        - name: wait-for-rabbitmq
          image: busybox:1.36
          command:
            [
              "sh",
              "-c",
              "until nc -z rabbitmq 5672; do echo \"waiting for rabbitmq...\";
                sleep 2; done;",
            ]
      containers:
        - name: gallery-ocr
          image: kisbogdan/gallery-ocr:latest
          envFrom:
            - secretRef:
                name: gallery-secrets
