name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    tags:
      - "v*"
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/build-push.yml"
      - "ansible/bme-okd.yaml"
      - "ansible/bme-okd/**"

jobs:
  build-gallery:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: kisbogdan/gallery

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            kisbogdan/gallery:latest
          labels: ${{ steps.meta.outputs.labels }}

  build-gallery-ocr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: kisbogdan/gallery-ocr

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile-ocr
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            kisbogdan/gallery-ocr:latest
          labels: ${{ steps.meta.outputs.labels }}

  deploy-openshift:
    needs: [ build-gallery, build-gallery-ocr ]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install OpenShift CLI
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4"

      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ vars.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ vars.OPENSHIFT_NAMESPACE }}

      - name: Install Ansible and k8s module
        run: pip install ansible kubernetes

      - name: Deploy using Ansible
        env:
          OPENSHIFT_NAMESPACE: ${{ vars.OPENSHIFT_NAMESPACE }}
          APP_POSTGRES_PASS: ${{ secrets.APP_POSTGRES_PASS }}
          APP_SEAWEED_ACCESS_KEY: ${{ secrets.APP_SEAWEED_ACCESS_KEY }}
          APP_SEAWEED_SECRET_KEY: ${{ secrets.APP_SEAWEED_SECRET_KEY }}
          APP_JWT_SECRET: ${{ secrets.APP_JWT_SECRET }}
          APP_RABBITMQ_PASS: ${{ secrets.APP_RABBITMQ_PASS }}
        run: ansible-playbook ansible/bme-okd.yaml
