name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/build-push.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: kisbogdan/gallery

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            kisbogdan/gallery:latest
          labels: ${{ steps.meta.outputs.labels }}

  deploy-openshift:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Install OpenShift CLI
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4"

      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ vars.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ vars.OPENSHIFT_NAMESPACE }}

      - name: Trigger OpenShift Rollout
        run: oc rollout restart deployment/${{ vars.OPENSHIFT_DEPLOYMENT }}
